version: '2'
services:
    zdravstvoapplication-app:
        image: zdravstvoapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://zdravstvoapplication-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=ZdravstvoApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://zdravstvoapplication-elasticsearch:9200
        ports:
            - 8080:8080
    zdravstvoapplication-mongodb:
        extends:
            file: mongodb.yml
            service: zdravstvoapplication-mongodb
    zdravstvoapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: zdravstvoapplication-elasticsearch
